apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customers
  name: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customers
    spec:
      containers:
      - image: gargimehendale/argo-jenkins-customers
        name: argo-jenkins-customers
        ports:
        - containerPort: 3000
          name: customer-port
