apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-frontend
  name: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-frontend
    spec:
      containers:
        - image: gargimehendale/argocd-demo-web-frontend
          name: argocd-demo-web-frontend
          env:
            - name: CUSTOMER_SERVICE_URL
              value: http://customers.default.svc
          ports:
            - containerPort: 80
              name: web-frontend
